# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pokpong/code_work/personal_proj/c_libs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pokpong/code_work/personal_proj/c_libs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pokpong/code_work/personal_proj/c_libs/CMakeFiles /home/pokpong/code_work/personal_proj/c_libs//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pokpong/code_work/personal_proj/c_libs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named basic_utils

# Build rule for target.
basic_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 basic_utils
.PHONY : basic_utils

# fast build rule for target.
basic_utils/fast:
	$(MAKE) $(MAKESILENT) -f lib/basic_utils/CMakeFiles/basic_utils.dir/build.make lib/basic_utils/CMakeFiles/basic_utils.dir/build
.PHONY : basic_utils/fast

#=============================================================================
# Target rules for targets named data_structures

# Build rule for target.
data_structures: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 data_structures
.PHONY : data_structures

# fast build rule for target.
data_structures/fast:
	$(MAKE) $(MAKESILENT) -f lib/data_structures/CMakeFiles/data_structures.dir/build.make lib/data_structures/CMakeFiles/data_structures.dir/build
.PHONY : data_structures/fast

#=============================================================================
# Target rules for targets named generics

# Build rule for target.
generics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generics
.PHONY : generics

# fast build rule for target.
generics/fast:
	$(MAKE) $(MAKESILENT) -f lib/generics/CMakeFiles/generics.dir/build.make lib/generics/CMakeFiles/generics.dir/build
.PHONY : generics/fast

#=============================================================================
# Target rules for targets named miscs

# Build rule for target.
miscs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miscs
.PHONY : miscs

# fast build rule for target.
miscs/fast:
	$(MAKE) $(MAKESILENT) -f lib/miscs/CMakeFiles/miscs.dir/build.make lib/miscs/CMakeFiles/miscs.dir/build
.PHONY : miscs/fast

#=============================================================================
# Target rules for targets named stream_utils

# Build rule for target.
stream_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stream_utils
.PHONY : stream_utils

# fast build rule for target.
stream_utils/fast:
	$(MAKE) $(MAKESILENT) -f lib/stream_utils/CMakeFiles/stream_utils.dir/build.make lib/stream_utils/CMakeFiles/stream_utils.dir/build
.PHONY : stream_utils/fast

#=============================================================================
# Target rules for targets named string_utils

# Build rule for target.
string_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 string_utils
.PHONY : string_utils

# fast build rule for target.
string_utils/fast:
	$(MAKE) $(MAKESILENT) -f lib/string_utils/CMakeFiles/string_utils.dir/build.make lib/string_utils/CMakeFiles/string_utils.dir/build
.PHONY : string_utils/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... basic_utils"
	@echo "... data_structures"
	@echo "... generics"
	@echo "... miscs"
	@echo "... stream_utils"
	@echo "... string_utils"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

